#this manifest is for creating pod from pulling image from private repo
apiVersion: v1 
kind: Pod 
metadata:
  name: nodeapp
  labels:
    app: nodeapp   
spec:
  containers:
  - name: nodeappc 
    image: mylandmarktech/nodejs-fe-app
    ports:
    - containerPort: 9981
  imagePullSecrets:
  - name: dhcred