#Node port manifest
apiVersion: v1 
kind: Service
metadata: 
  name: websvc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: webapp 
  ports:
  - targetPort: 8080 
    port: 80 
    nodePort: 32000