apiVersion: apps/v1 
kind: ReplicaSet
metadata: 
  name: myapp-rs 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: myapp 
  template:
    metadata:
      name: myapp-c
      labels:
        app: myapp 
    spec:
      containers:
      - name: web-c 
        image: mylandmarktech/hello  
        ports:
        - containerPort: 80  

