#manifest for creating ClusterIP service
apiVersion: v1 
kind: Service
metadata: 
  name: webappsvc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: webapp 
  ports:
  - targetPort: 8080 
    port: 80 
    
---
  apiVersion: v1 
  kind: Service
  metadata: 
     name: mywebappsvc
     namespace: dev
  spec:
    type: ClusterIP
    selector:
     app: mywebapp 
    ports:
     - targetPort: 8080 
     - port: 80